import * as express from "express";
import * as bodyParser from "body-parser";
import * as helmet from "helmet";
import { commentRouter } from "./comment";
import { postRouter } from "./post";
const app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(helmet());
app.use("/api/v1/comments", commentRouter);
app.use("/api/v1/posts", postRouter);
app.listen(8080);
export { app };
